name: speakerr
options:
  bundleIdPrefix: com.brimell
  deploymentTarget:
    macOS: "13.0"
  xcodeVersion: "15.0"

targets:
  speakerr:
    type: application
    platform: macOS
    sources:
      - speakerr
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.brimell.speakerr
        PRODUCT_NAME: speakerr
        MACOSX_DEPLOYMENT_TARGET: "13.0"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        INFOPLIST_FILE: speakerr/Info.plist
        CODE_SIGN_ENTITLEMENTS: speakerr/speakerr.entitlements
        SWIFT_VERSION: "5.9"
        ENABLE_HARDENED_RUNTIME: NO
        CODE_SIGN_IDENTITY: "-"
    info:
      path: speakerr/Info.plist
    entitlements:
      path: speakerr/speakerr.entitlements
